name: Ma première CI/CD

on:
  push:
    tags:
      - "dev-"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installer les dépendances
        run: npm install

      
      - name: Lint syntaxe
        run: npm run lint
        
      - name: Lancer les tests
        run: npm test
        # optionnel si tu n’as pas de tests
        # continue-on-error: truesqdvz
      - name: SCA - Audit des dépendances
        run: npm audit --audit-level=hig

      - name: SAST - Scan du code source (Semgrep)
        uses: semgrep/semgrep-action@v1
        with:
           config: p/javascrip


      - name : C'est pas bon!
        if: failure()
        run: |
         echo : "Echec"
         curl -H "Content-Type: application/json" \
              -d '{
                   "username": "GitHub Actions",
                   "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                   "content": "❌ **Échec du Workflow !**\n\n**Projet :** `${{ github.repository }}`\n**Branche :** `${{ github.ref_name }}`\n**Action :** [Voir le détail de l erreur](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\n**Message :** L exécution a rencontré une erreur critique."
                  }' \
         https://discord.com/api/webhooks/1472873032505753601/vkvWUhArxJRFAI-vtqEjhS43llrU_enUwjQgMh7JoKFDADRFRSjdwhCpEfHmXNrMIQ1N

  deploy:
    name : Deploiment 
    runs-on: ubuntu-latest
    
    steps:
      - uses: ttskch/render-deploy@v1.0.0
        with:
          api-key: rnd_jf6omqccRqoPFgtAcM2MbY7RQ5R2
          service-id: srv-d5pibtpr0fns73f2amh0

  
